#version 430 core
#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct ComputeCell {
    vec4 positionAndMass;
    vec4 velocity;
    vec4 acceleration;
    vec4 orientation;
    vec4 angularVelocity;
    vec4 angularAcceleration;
    vec4 signallingSubstances;
    int modeIndex;
    float age;
    float toxins;
    float nitrates;
    uint64_t uniqueID;
    uint64_t justSplit;
    uint padding2[4];
};

layout(std430, binding = 0) buffer CellBuffer {
    ComputeCell cells[];
};

layout(std430, binding = 1) buffer CellCountBuffer {
    uint cellCount;
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= cellCount) return;
    cells[index].justSplit = 0;
} 