#version 430 core

layout(local_size_x = 64) in;

struct ComputeCell {
    // Physics:
    vec4 positionAndMass; // x, y, z, mass
    vec3 velocity;
    vec3 acceleration;
    vec4 orientation; // angular stuff in quaternion to prevent gimbal lock
    vec4 angularVelocity;
    vec4 angularAcceleration;
    // Internal:
    vec4 signallingSubstances; // 4 substances for now
    int modeIndex;
    float age; // also used for split timer
    float toxins;
    float nitrates;
};

struct Adhesion {
    vec4 restOrientationOffset;
    ivec2 connectedCells;
    int modeIndex; // To get the mode's adhesion settings
    float padding;
};

layout(std430, binding = 0) readonly buffer CellBuffer {
    ComputeCell cells[];
};

layout(std430, binding = 1) readonly buffer AdhesionBuffer {
    Adhesion adhesions[];
};

layout(std430, binding = 2) writeonly buffer LineVertexBuffer {
    vec3 lineVertices[]; // 2 per adhesion
};

layout(std430, binding = 3) buffer AdhesionCountBuffer {
    uint adhesionCount;
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= adhesionCount) return;

    Adhesion adhesion = adhesions[i];

    int a = adhesion.connectedCells.x;
    int b = adhesion.connectedCells.y;

    vec3 posA = cells[a].positionAndMass.xyz;
    vec3 posB = cells[b].positionAndMass.xyz;

    // Store start and end points
    lineVertices[i * 2 + 0] = posA;
    lineVertices[i * 2 + 1] = posB;
}
