#pragma once

// Auto-generated version file
// Do not edit manually - this file is generated by increment_version.ps1

namespace Version
{
    constexpr int MAJOR = 0;
    constexpr int MINOR = 0;
    constexpr int PATCH = 0;
    constexpr const char* STRING = "0.0.0";
    constexpr const char* FULL_STRING = "0.0.0-alpha";
    constexpr const char* BUILD_DATE = __DATE__;
    constexpr const char* BUILD_TIME = __TIME__;
    constexpr bool IS_ALPHA = true;
}
